version: '3.0'

services:
  app: 
    build:
      context: .
      dockerfile: ./Dockerfile
      target: development
    command: npm run start:dev
    depends_on:
      - rabbitmq
    env_file:
      - .env.development
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - '3000:3000'
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - '5672:5672'
      - '15672:15672'