version: '3.8'

services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    hostname: rabbitmq
    volumes:
      - /var/lib/rabbitmq
    ports:
      - '5672:5672'
      - '15672:15672'

  message: 
    build:
      context: .
      dockerfile: ./apps/message/Dockerfile
      target: development
    command: npm run start:dev message
    depends_on:
      - rabbitmq
    env_file:
      - ./apps/message/.env
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
  gateway: 
    build:
      context: .
      dockerfile: ./apps/gateway/Dockerfile
      target: development
    command: npm run start:dev gateway
    depends_on:
      - message
      - rabbitmq
    env_file:
      - ./apps/gateway/.env
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - '3000:3000'
  