version: '3.8'

services:
  message: 
    # build:
    #   context: .
    #   dockerfile: ./apps/message/Dockerfile
    #   target: development
    image: thethtet/message-message:latest
    command: npm run start:dev message
    depends_on:
      - rabbitmq
      - mongodb
    env_file:
      - ./apps/message/.env
  gateway: 
    # build:
    #   context: .
    #   dockerfile: ./apps/gateway/Dockerfile
    #   target: development
    image: thethtet/message-gateway:latest
    command: npm run start:dev gateway
    depends_on:
      - message
      - rabbitmq
    env_file:
      - ./apps/gateway/.env
    ports:
      - '3000:3000'
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    hostname: rabbitmq
    volumes:
      - /var/lib/rabbitmq
    ports:
      - '5672:5672'
      - '15672:15672'
  mongodb:
    image: mongo:6-jammy
    ports:
      - '27017:27017'
    volumes:
      - dbdata6:/data/db
volumes:
  dbdata6:
